make: dev

dev:
	g++ -O2 -DOSVARP dev_pow_proj.cpp
	./a.out

roll:
	g++ -O2 -DOSVARP pow_proj.cpp
	./a.out 
bostan:
	g++ -O2 -DOSVARP bostanMori.cpp
	./a.out 
stolen:
	g++ -O2 stolen.cpp
	./a.out
cmp: stolen roll
compo:
	g++ -O2 -DOSVARP composition.cpp
	./a.out